# Generated by Django 5.2.9 on 2026-01-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_28027', '0002_contactmessage_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='review_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV Series', 'TV Series')], default='Movie', max_length=20),
            preserve_default=False,
        ),
    ]
