# Generated by Django 5.2.9 on 2026-01-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_28027', '0003_blog_review_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sentiment',
        ),
    ]
