# Generated by Django 5.2.9 on 2026-01-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_28027', '0004_remove_blog_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for your review', null=True, upload_to='blog_covers/'),
        ),
    ]
