# Generated by Django 5.2.9 on 2026-02-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_28027', '0005_blog_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(),
        ),
    ]
