# Generated by Django 5.2.9 on 2026-02-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_28027', '0006_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
    ]
